### ISSUE TITLE
[minutes.py] fix the issues with specific encoding.

### ISSUE THREAD

**Issue by karlcow** [karlcow/webcompat#4]
```
→ python minutes.py

Traceback (most recent call last):
  File "minutes.py", line 207, in <module>
    sys.exit(main())
  File "minutes.py", line 203, in main
    foo = parse_minutes(md_content['text'], 'mw')
  File "minutes.py", line 127, in parse_minutes
    description += '{0} '.format(line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 167: ordinal not in range(128)
```

It was due to this sentence

```
Let's submit a proposal to do either a 90 minute or 3 hour workshop at Fluent: http://fluentconf.com/fluent2015/public/cfp/350. CFP ends October 27th. Conf is April 20–22, 2015 
```

and more specifically the character `—`.

**Comment by karlcow** [comment]
fixed
